set CMAKE_FLAGS=-DCMAKE_INSTALL_PREFIX=%PREFIX%
set CMAKE_FLAGS=%CMAKE_FLAGS% -DREADDY_BUILD_SHARED_COMBINED:BOOL=ON
set CMAKE_FLAGS=%CMAKE_FLAGS% -DCMAKE_BUILD_TYPE=Release

mkdir build
cd build
cmake .. %CMAKE_FLAGS%
make
make install
