{% set name = "readdy" %}

package:
  name: {{ name }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}
source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  rpaths:
    - lib/
    - lib/python3.9/site-packages/{{ name }}  # [py==39]
    - lib/python3.9/site-packages/{{ name }}/readdy_plugins  # [py==39]
    - lib/python3.8/site-packages/{{ name }}  # [py==38]
    - lib/python3.8/site-packages/{{ name }}/readdy_plugins  # [py==38]
    - lib/python3.7/site-packages/{{ name }}  # [py==37]
    - lib/python3.7/site-packages/{{ name }}/readdy_plugins  # [py==37]
    - lib/python3.6/site-packages/{{ name }}  # [py==36]
    - lib/python3.6/site-packages/{{ name }}/readdy_plugins  # [py==36]

requirements:
  host:
    - python
    - h5py
    - hdf5
    - bzip2
    - numpy
    - zlib 1.2.*

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  run:
    - intel-openmp # [osx]
    - python
    - numpy
    - h5py
    - pint
    - tqdm
    - hdf5
    - zlib 1.2.*

test:
  imports:
    - readdy
  requires:
    - nose
