{% set name = "readdy" %}

package:
  name: {{ name }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}
source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  rpaths:
    - lib/

requirements:
  host:
    - python
    - h5py
    - hdf5
    - bzip2
    - numpy >=1.14
    - zlib 1.2.*
    - blosc 1.21.1

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - spdlog >=1.15.0
    - nlohmann_json >=3.12.0
    - fmt >=11.2.0
    - pybind11 >=3.0.0

  run:
    - intel-openmp # [osx]
    - python
    - numpy >=1.14
    - h5py
    - pint
    - tqdm
    - hdf5
    - zlib 1.2.*

test:
  imports:
    - readdy
  requires:
    - nose
