{% set name = "readdy" %}

package:
  name: {{ name }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'dev') }}
source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  rpaths:
    - lib/
    - lib/readdy_plugins

requirements:
  host:
    - python
    - h5py
    - hdf5
    - bzip2
    - numpy >=1.14
    - zlib 1.2.*
    - spdlog ==1.10.0
    - nlohmann_json <=3.10.3
    - pybind11
    - blosc
    - fmt ==8.1.1
    - catch2

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja

  run:
    - intel-openmp # [osx]
    - python
    - numpy >=1.14
    - h5py
    - pint
    - tqdm
    - hdf5
    - zlib 1.2.*
    - blosc

test:
  imports:
    - readdy
  requires:
    - nose
