SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy2/main/io")

# hdf5
# SET(HDF5_USE_STATIC_LIBRARIES OFF)
FIND_PACKAGE(HDF5 COMPONENTS CXX REQUIRED)
MESSAGE(STATUS "HDF5_FOUND: ${HDF5_FOUND}")

# includes
SET(IO_INCLUDE_DIRS "${MODEL_INCLUDE_DIRS};${HDF5_INCLUDE_DIRS}" CACHE INTERNAL "IO Include dirs")

# libraries
SET(READDY_IO_LIBRARIES "${READDY_MODEL_LIBRARIES};${HDF5_LIBRARIES}" CACHE INTERNAL "IO Libraries")
LIST(REMOVE_DUPLICATES READDY_IO_LIBRARIES)

# sources
LIST(APPEND READDY_IO_SOURCES "${SOURCES_DIR}/IOUtils.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_IO_SOURCES})