SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy/main/common")

SET(SPDLOG_INCLUDE_DIR "${READDY_GLOBAL_DIR}/libraries/spdlog/include")

FIND_PACKAGE(Threads REQUIRED)

# include dirs
SET(COMMON_INCLUDE_DIRS "${READDY_GLOBAL_INCLUDE_DIR};${SPDLOG_INCLUDE_DIR}" CACHE INTERNAL "Common include dirs")

# dependent libraries
SET(READDY_COMMON_LIBRARIES "${Boost_LIBRARIES}" CACHE INTERNAL "Common libraries")

# sources
LIST(APPEND READDY_COMMON_SOURCES "${SOURCES_DIR}/Utils.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_COMMON_SOURCES})
