SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy/main/model")

SET(MODEL_INCLUDE_DIRS "${COMMON_INCLUDE_DIRS}" CACHE INTERNAL "Model include dirs")

# libraries
SET(READDY_MODEL_LIBRARIES "${READDY_COMMON_LIBRARIES}" CACHE INTERNAL "Model libraries")

# includes
SET(MODEL_INCLUDE_DIRS "${COMMON_INCLUDE_DIRS}" CACHE INTERNAL "Model include dirs")

# sources
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/KernelContext.cpp")
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/Particle.cpp")
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/Vec3.cpp")
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/Kernel.cpp")
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/Observables.cpp")
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/Potentials.cpp")
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/Reactions.cpp")
# internal sources
LIST(APPEND READDY_MODEL_SOURCES "${SOURCES_DIR}/_internal/ObservableWrapper.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_MODEL_SOURCES})