SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy/main/common")

FIND_PACKAGE(Threads REQUIRED)
SET(Boost_USE_STATIC_LIBS OFF)
SET(Boost_USE_MULTITHREADED ON)
SET(Boost_USE_STATIC_RUNTIME OFF)
FIND_PACKAGE(Boost 1.57 COMPONENTS system filesystem log thread REQUIRED)

# include dirs
SET(COMMON_INCLUDE_DIRS "${READDY_GLOBAL_INCLUDE_DIR};${Boost_INCLUDE_DIRS}" CACHE INTERNAL "Common include dirs")

# dependent libraries
SET(READDY_COMMON_LIBRARIES "${Boost_LIBRARIES}" CACHE INTERNAL "Common libraries")

# sources
LIST(APPEND READDY_COMMON_SOURCES "${SOURCES_DIR}/Utils.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_COMMON_SOURCES})
