SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy2/main/io")

# hdf5
SET(HDF5_USE_STATIC_LIBRARIES OFF)
FIND_PACKAGE(HDF5 COMPONENTS CXX REQUIRED)

# includes
SET(IO_INCLUDE_DIRS "${COMMON_INCLUDE_DIRS} ${HDF5_INCLUDE_DIRS}" CACHE INTERNAL "IO Include dirs" FORCE)

# libraries
SET(READDY_IO_LIBRARIES "${READDY_COMMON_LIBRARIES};${HDF5_CXX_LIBRARIES}")

# sources
LIST(APPEND READDY_IO_SOURCES "${SOURCES_DIR}/IOUtils.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_IO_SOURCES})