SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy2/main/io")

# includes
SET(IO_INCLUDE_DIRS "${COMMON_INCLUDE_DIRS}" CACHE INTERNAL "IO Include dirs" FORCE)

# sources
LIST(APPEND READDY_IO_SOURCES "${SOURCES_DIR}/ReaDDy_IO.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_IO_SOURCES})