SET(SOURCES_DIR "${READDY_GLOBAL_DIR}/readdy2/main/plugin")

# includes
SET(PLUGIN_INCLUDE_DIRS "${COMMON_INCLUDE_DIRS};${Boost.DLL_INCLUDE_DIRS}" CACHE INTERNAL "Plugin include dirs" FORCE)

# libraries
SET(READDY_PLUGIN_LIBRARIES "${READDY_COMMON_LIBRARIES};${CMAKE_DL_LIBS}")

# sources
LIST(APPEND READDY_PLUGIN_SOURCES "${SOURCES_DIR}/KernelProvider.cpp")
LIST(APPEND READDY_PLUGIN_SOURCES "${SOURCES_DIR}/KernelPluginDecorator.cpp")
LIST(APPEND READDY_PLUGIN_SOURCES "${SOURCES_DIR}/Program.cpp")

# all sources
LIST(APPEND READDY_ALL_SOURCES ${READDY_PLUGIN_SOURCES})